name: advanced_xo_game
description: Advanced Tic Tac Toe game with enhanced UI/UX, adaptive AI,
  undo/redo and game history using BLoC.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  path: ^1.8.0
  sqflite: ^2.0.0+4
  shared_preferences: ^2.2.2
  audioplayers: ^5.2.1
  vibration: ^2.0.0
  share_plus: ^7.2.1
  fl_chart: ^0.66.0
  url_launcher: ^6.2.2
  path_provider: ^2.1.1
  intl: ^0.18.1
  file_picker: ^10.3.3
  confetti: ^0.7.0
  lottie: ^3.0.0

dev_dependencies:
  flutter_launcher_icons: "^0.14.3"
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.png
    - assets/fonts/
    - assets/sounds/



  fonts:
    - family: Inter
      fonts:
        - asset:  assets/fonts/Inter-Light.ttf
          weight: 300
        - asset:  assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset:  assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset:  assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset:  assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset:  assets/fonts/Inter-SemiBold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset:  assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset:  assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset:  assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset:  assets/fonts/Poppins-SemiBold.ttf
          weight: 600
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Light.ttf
          weight: 300
        - asset: assets/fonts/Almarai-Regular.ttf
          weight: 400
        
        - asset: assets/fonts/Almarai-Bold.ttf
          weight: 700
        - asset: assets/fonts/Almarai-ExtraBold.ttf
          weight: 800    
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-Light.ttf
          weight: 300
        - asset: assets/fonts/NunitoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NunitoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/NunitoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NunitoSans-ExtraBold.ttf
          weight: 800          
    - family: InterDisplay
      fonts:
        - asset: assets/fonts/InterDisplay-Light.ttf
          weight: 300
        - asset: assets/fonts/InterDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/InterDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/InterDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/InterDisplay-ExtraBold.ttf
          weight: 800   
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.otf
          weight: 400
        - asset: assets/fonts/Manrope-Light.otf
          weight: 300
        - asset: assets/fonts/manrope-medium.otf
          weight: 500
        - asset: assets/fonts/Manrope-Bold.otf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.otf
          weight: 800    
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
          weight: 400
        - asset: assets/fonts/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-ExtraBold.ttf
          weight: 800        
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFPRODISPLAY-REGULAR.OTF
          weight: 400
        - asset: assets/fonts/SFPRODISPLAY-MEDIUM.OTF
          weight: 500
        - asset: assets/fonts/SFPRODISPLAY-BOLD.OTF
          weight: 700        
flutter_launcher_icons:
  android: true
  ios: true
  web: true
  macos: true
  windows: true

  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
